data:
  train_path: "data/raw/train.csv"
  test_path: "data/raw/test.csv"
  test_target_path: "data/raw/gender_submission.csv"
  target: "Survived"

preprocess:
  num_cols: ["Age", "Fare", "Parch", "SibSp"]
  cat_cols: ["Sex", "Embarked"]
  drop_cols: ["PassengerId", "Name", "Cabin"]

cv: 
  do: false
  folds: 5
  scoring: 'accuracy'

model:
  name: "RF"
  save: true
  save_path: "models/model.pkl"


SGD:
  max_iter: 1000
  tol: 0.001
  random_state: 42

RF:
  n_estimators: 200
  max_depth: 30
  max_features: 'sqrt'
  min_samples_leaf: 4
  min_samples_split: 10


search:
  do: false
  cv: 5
  scoring: 'accuracy'
  param_grid:
    model__n_estimators: [50, 100, 200]
    model__max_depth: [5, 10, 30, 50]
    model__min_samples_split: [2, 5, 10, 20]
    model__min_samples_leaf: [1, 2, 4, 8]
    model__max_features: ["sqrt", "log2"]

predict:
  model_path: "models/model.pkl"
  submit_path: "data/submissions/submission.csv"
  save_predictions: false


